export const SEARCH_REPOS_REQUEST:String = 'SEARCH_REPOS_REQUEST';
export const SEARCH_REPOS_RESPONSE:String = 'SEARCH_REPOS_RESPONSE';

export const SEARCH_USERS_REQUEST:String = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_RESPONSE:String = 'SEARCH_USERS_RESPONSE';

export const SEARCH_CLEAR:String = 'SEARCH_CLEAR';